Test/pet endpoints
PiotrNowek/TestRestApi pull request #6
Opened 2024-07-10 18:17 UTC by PiotrNowek

2024-07-13 09:39 UTC, Michal-Bandyszak requested changes

2024-07-13 09:39 UTC, Michal-Bandyszak commented on tests/api/pet/test_pet.py
> +def function_get_pet_by_id(pet_id):
Tutaj zmieniłbym nazwę funkcji na "get_pet_by_id". przedrostek "function" nie jest tu potrzebny

2024-07-13 09:39 UTC, Michal-Bandyszak commented
Zrób małą poprawkę i będziemy mogli zrobić merge

2024-07-16 10:49 UTC, PiotrNowek commented on tests/api/pet/test_pet.py
> +def function_get_pet_by_id(pet_id):
Zrobione

2024-07-17 17:34 UTC, merged